name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets. github_token }}
        ADD_LABEL: "approved"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag akpaul1991/app-backend:v.08
    - name: Log in to Docker Hub and push
      run: docker login -u akpaul1991 -p ${{ secrets.DOCKER_TOKEN }} && docker push akpaul1991/app-backend:v.08
